# .github/workflows/pr_auto_merger.yml

name: 自动验证并合并数据类 PR (Auto-Validate and Merge Data PRs)

env:
  # 合并任务执行间隔 (分钟)，注意：此参数仅供参考，实际调度由下面的 cron 表达式决定
  MERGE_INTERVAL_MINUTES: 30

on:
  schedule:
    # UTC 时间，每天的 1:00 到 16:59，每 30 分钟执行一次
    - cron: '*/30 1-16 * * *'
  workflow_dispatch:

# 设置并发控制，确保同一时间只有一个合并任务在运行
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-validate-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码 (Checkout Code)
        uses: actions/checkout@v4

      - name: 设置 Python (Set up Python)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 安装项目依赖 (Install Dependencies)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 验证并合并 PR (Validate and Merge PRs)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
        run: bash .github/scripts/pr_auto_merger.sh
